In [1]:
import pandas as pd
import os
import glob

# Ruta a la carpeta
path = 'LinkedIn/Data'  


# Construye la ruta completa y busca todos los archivos CSV en la carpeta
all_files = glob.glob(os.path.join(path, "*.csv"))

print(all_files)

# Lista para almacenar cada DataFrame leído de cada archivo CSV
dfs = []

# Itera sobre los archivos encontrados y los añade a la lista de DataFrames
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    dfs.append(df)

# Combina todos los DataFrames de la lista en uno solo
combined_df = pd.concat(dfs, axis=0, ignore_index=True)

# Muestra el DataFrame combinado
print(combined_df)
#combined_df.to_excel("_output/desa_linked_df.xlsx")

['LinkedIn/Data\\Actuación_09-03-2024-22-06-41.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-07-09.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-07-41.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-08-13.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-08-44.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-09-16.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-09-49.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-10-11.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-10-30.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-11-05.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-11-31.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-12-00.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-12-30.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-12-55.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-13-27.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-14-01.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-14-24.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-15-01.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-15-29.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-16-01.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-16-30.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-17-00.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-17-22.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-17-50.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-18-26.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-18-55.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-19-21.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-19-46.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-20-09.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-20-38.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-21-00.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-21-17.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-21-53.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-22-27.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-23-00.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-23-23.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-23-52.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-24-12.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-24-56.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-25-14.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-25-44.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-26-20.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-26-47.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-27-14.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-27-39.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-28-14.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-28-43.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-29-04.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-29-39.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-29-59.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-30-28.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-30-49.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-31-13.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-31-32.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-32-07.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-32-36.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-32-56.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-33-31.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-33-52.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-34-09.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-34-42.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-35-07.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-35-27.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-35-44.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-36-20.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-36-48.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-37-13.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-37-38.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-38-07.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-38-27.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-39-04.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-39-32.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-40-04.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-40-40.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-41-12.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-41-40.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-42-27.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-43-01.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-43-29.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-43-47.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-44-14.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-44-40.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-45-09.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-45-35.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-45-59.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-46-18.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-46-46.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-47-16.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-47-50.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-48-23.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-48-45.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-49-23.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-49-55.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-50-21.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-50-42.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-51-13.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-51-31.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-51-55.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-52-12.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-52-33.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-53-10.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-53-33.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-54-05.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-54-40.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-55-10.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-55-40.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-56-05.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-56-26.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-56-56.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-57-38.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-58-03.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-58-28.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-58-59.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-59-20.csv', 'LinkedIn/Data\\Actuación_09-03-2024-22-59-54.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-00-20.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-00-45.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-01-17.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-01-36.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-02-02.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-02-28.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-02-49.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-03-23.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-04-01.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-04-28.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-05-02.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-05-25.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-05-46.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-06-28.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-06-52.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-07-16.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-07-45.csv', 'LinkedIn/Data\\Actuación_09-03-2024-23-08-14.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-00-22.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-00-52.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-01-27.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-01-52.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-02-28.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-02-59.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-03-20.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-03-40.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-04-08.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-04-37.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-05-03.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-05-26.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-05-54.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-06-27.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-06-57.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-07-29.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-07-50.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-08-21.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-08-55.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-09-29.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-09-57.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-10-26.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-10-53.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-11-11.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-11-35.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-12-06.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-12-31.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-12-51.csv', 'LinkedIn/Data\\Administración de contratos_01-04-2024-00-13-25.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-15-33.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-16-09.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-16-33.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-17-06.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-17-32.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-17-56.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-18-29.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-19-01.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-19-34.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-20-03.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-20-36.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-20-52.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-21-20.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-21-43.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-22-10.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-22-31.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-23-07.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-23-34.csv', 'LinkedIn/Data\\Administración de contratos_16-04-2024-06-23-52.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-41-55.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-42-35.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-42-58.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-43-19.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-43-44.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-44-11.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-44-34.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-44-58.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-45-30.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-45-59.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-46-20.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-46-48.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-47-16.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-47-35.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-48-10.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-48-35.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-49-10.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-49-29.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-50-18.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-50-45.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-51-11.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-51-46.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-52-24.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-52-57.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-53-30.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-53-49.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-54-18.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-54-41.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-55-07.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-55-36.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-56-07.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-56-42.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-57-03.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-57-27.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-57-58.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-58-18.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-58-59.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-59-26.csv', 'LinkedIn/Data\\Administración de contratos_31-03-2024-23-59-50.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-48-05.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-48-43.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-49-18.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-49-53.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-50-29.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-51-04.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-51-39.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-52-15.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-52-50.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-53-17.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-53-54.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-54-32.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-55-07.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-55-43.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-56-19.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-56-54.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-57-31.csv', 'LinkedIn/Data\\Administración de Empresas_09-03-2024-21-58-05.csv', 'LinkedIn/Data\\Antropología_16-03-2024-11-59-12.csv', 'LinkedIn/Data\\Antropología_16-03-2024-11-59-35.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-00-06.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-00-34.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-01-08.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-01-27.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-01-53.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-02-27.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-02-50.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-03-21.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-03-39.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-04-06.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-04-41.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-05-15.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-05-38.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-06-04.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-06-36.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-07-00.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-07-21.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-37-50.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-38-19.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-38-51.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-39-16.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-39-37.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-40-00.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-40-17.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-40-44.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-41-03.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-41-25.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-41-59.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-42-28.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-43-02.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-43-27.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-43-43.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-44-16.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-44-49.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-45-20.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-45-51.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-46-20.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-46-45.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-47-28.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-47-45.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-48-05.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-48-35.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-48-46.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-49-16.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-49-50.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-50-10.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-50-36.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-51-13.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-51-42.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-52-05.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-52-38.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-53-07.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-53-31.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-54-03.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-54-37.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-55-03.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-55-26.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-55-55.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-56-36.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-57-00.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-57-12.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-57-40.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-58-14.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-58-31.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-58-49.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-59-21.csv', 'LinkedIn/Data\\Antropología_16-03-2024-12-59-55.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-00-32.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-00-57.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-01-23.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-01-59.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-02-23.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-02-52.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-03-05.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-03-32.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-03-56.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-04-28.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-05-05.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-05-40.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-06-14.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-06-48.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-07-22.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-07-46.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-08-04.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-08-35.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-08-54.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-09-32.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-10-09.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-10-29.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-10-47.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-11-22.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-11-54.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-12-15.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-12-42.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-13-05.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-13-39.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-14-20.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-14-54.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-15-27.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-15-48.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-16-14.csv', 'LinkedIn/Data\\Antropología_16-03-2024-13-16-45.csv', 'LinkedIn/Data\\Antropología_16

In [9]:
combined_df.to_excel("_output/desa_linked_df.xlsx")

In [2]:
combined_df.head(5)

,Unnamed: 0,Title,Link,Company,Location,Time_on,Applies,Working_day,Experience,Company_size,Apts,Description,Keyword,Company_area
0,0,Práctica Periodismo,https://www.linkedin.com/jobs/view/3840366533/...,Better Commerce,"Las Condes, Región Metropolitana de Santiago, ...",hace 1 semana,53 solicitudes,Prácticas,NaN,De 51 a 200 empleados,"['Blogging', 'Comercio', 'Comercio electrónico...",En Better Commerce nos dedicamos a la creación...,Actuación,NaN
1,0,Alumno/a en práctica Periodismo o Diseño,https://www.linkedin.com/jobs/view/3842927389/...,Axis Desarrollos Constructivos SA,"Gran Santiago, Región Metropolitana de Santiag...",hace 1 semana,37 solicitudes,Jornada completa,NaN,De 1.001 a 5.000 empleados,"['Comunicaciones internas', 'Creación de conte...",Empresa de la industria de la construcción req...,Actuación,NaN
2,0,Práctica Profesional Marketing,https://www.linkedin.com/jobs/view/3840396213/...,Better Commerce,"Las Condes, Región Metropolitana de Santiago, ...",hace 1 semana,60 solicitudes,Prácticas,NaN,De 51 a 200 empleados,"['Comercio', 'Comercio electrónico', 'Fitness'...",En Better Commerce nos dedicamos a la creación...,Actuación,NaN
3,0,Analista Trade Marketing - Canal Tradicional,https://www.linkedin.com/jobs/view/3826789824/...,Empresas Iansa,"Las Condes, Región Metropolitana de Santiago, ...",hace 3 semanas,Más de 100 solicitudes,Jornada completa,Intermedio,De 501 a 1.000 empleados,"['Marketing de canal', 'Marketing de productos...",Para Empresas Iansa sus colaboradores son el c...,Actuación,NaN
4,0,PENTESTER SENIOR,https://www.linkedin.com/jobs/view/3840266677/...,XPoint Cybersecurity,"Gran Santiago, Región Metropolitana de Santiag...",hace 1 semana,57 solicitudes,Jornada completa,NaN,De 11 a 50 empleados,"['Saber', 'Skill Development', 'Todos los filt...",OPORTUNIDAD PROFESIONAL EN CIBERSEGURIDAD \n\n...,Actuación,NaN

In [3]:
combined_df.columns

Index(['Unnamed: 0', 'Title', 'Link', 'Company', 'Location', 'Time_on',
       'Applies', 'Working_day', 'Experience', 'Company_size', 'Apts',
       'Description', 'Keyword', 'Company_area'],
      dtype='object')

In [4]:
master_df = combined_df.drop('Unnamed: 0', axis=1)
master_df.columns

Index(['Title', 'Link', 'Company', 'Location', 'Time_on', 'Applies',
       'Working_day', 'Experience', 'Company_size', 'Apts', 'Description',
       'Keyword', 'Company_area'],
      dtype='object')

In [21]:
filtered_df = master_df.drop_duplicates(subset=['Title', 'Description', 'Company'], keep='first', inplace=False)
print(master_df.shape)
filtered_df = filtered_df[filtered_df['Company_area'] == "Servicios y consultoría de TI"]
print(filtered_df.shape)
#filtered_df.to_excel("_output/desa_linked_df.xlsx")

(7706, 13)
(784, 13)

In [22]:
import ast
from collections import Counter

# Filtrar las filas que tienen valores no nulos en la columna 'Apts'
filtered_df = filtered_df.dropna(subset=['Apts'])

# Convertir las cadenas de caracteres a listas
filtered_df['Apts'] = filtered_df['Apts'].apply(ast.literal_eval)

# # Crear una lista plana de todos los elementos en la columna 'Apts'
# apts_list = [apt for sublist in filtered_df['Apts'] for apt in sublist]

apts_list = []

# Iterar sobre cada fila en la columna 'Apts'
for sublist in filtered_df['Apts']:
    # Iterar sobre cada elemento en la sublista
    # sublist ['Blogging', 'Comercio', 'Comercio electrónico', 'Fitness', 'Marketing', 'Publicidad de búsqueda', 'Saldo', 'Ultimate', 'User personas']
    for apt in sublist:
        # Agregar el elemento a la lista plana
        # Apt 'Blogging'
        apts_list.append(apt)

# Contar la frecuencia de cada elemento
apt_counts = Counter(apts_list)

# Obtener los elementos más comunes y sus recuentos
top_apts = apt_counts.most_common()

print(top_apts)

[('Todos los filtros', 211), ('Inglés', 173), ('Comunicación', 157), ('Java', 93), ('Desarrollo de software', 86), ('SQL', 80), ('Resolución de problemas', 78), ('Hojas de estilos en cascada (CSS)', 78), ('Bases de datos', 75), ('Python', 75), ('JavaScript', 67), ('Ciencias de la computación', 62), ('Desarrollo web back end', 51), ('Capacidad de análisis', 46), ('Amazon Web Services (AWS)', 43), ('Microsoft Azure', 43), ('Angular', 43), ('Microservicios', 40), ('C#', 36), ('Extraer, transformar y cargar (ETL)', 35), ('Google Cloud', 34), ('Liderazgo de equipos', 32), ('Programación en C', 30), ('Negociación', 29), ('HTML', 28), ('Spring Boot', 28), ('Automatización de pruebas', 28), ('iOS', 28), ('Transferencia de Estado Representacional (REST)', 28), ('DevOps', 27), ('Atención al detalle', 27), ('Ciencia de datos', 27), ('Desarrollo front end', 27), ('Programación', 26), ('Modelo-Vista-Controlador (MVC)', 26), ('Trabajo en equipo', 25), ('Computación en la nube', 25), ('Android', 25), ('Microsoft SQL Server', 24), ('Desarrollo de aplicaciones móviles', 24), ('TypeScript', 23), ('Prueba unitaria', 23), ('Presentaciones', 22), ('Ingeniería de datos', 22), ('Metodologías ágiles', 22), ('Aseguramiento de la calidad', 22), ('Git', 21), ('Kubernetes', 21), ('React.js', 21), ('Aplicaciones móviles', 21), ('Node.js', 20), ('Investigación', 20), ('Linux', 19), ('Terraform', 19), ('Resolución de incidencias', 19), ('Ventas', 19), ('Analítica de datos', 18), ('Swift (lenguaje de programación)', 18), ('Programación de aplicaciones', 17), ('Automatización', 17), ('Desarrollo de iOS', 17), ('Programación orientada a objetos (POO)', 17), ('Ruby', 17), ('Casos de prueba', 17), ('Dirección de equipos', 16), ('Ruby on Rails', 16), ('Documentación', 16), ('.NET Framework', 16), ('Fiabilidad', 15), ('Gestión de proyectos', 15), ('PostgreSQL', 15), ('Modelado de datos', 15), ('Soporte técnico', 15), ('Tecnología de la información', 15), ('Almacenamiento de datos', 15), ('Inteligencia artificial', 15), ('Objective-C', 15), ('Oracle Database', 14), ('SAP HANA', 14), ('Diseño de la interfaz de usuario', 14), ('Metodologías Agile y Waterfall', 14), ('Desarrollo de Android', 14), ('Go', 13), ('Infraestructura en la nube', 13), ('Habilidades sociales', 13), ('Necesidades empresariales', 13), ('Documentación técnica', 13), ('Comunicación escrita', 13), ('Marketing', 13), ('Integración continua', 13), ('Modelo–vista–modelo de vista (MVVM)', 13), ('Scrum', 12), ('Productos SAP', 12), ('Microsoft Excel', 12), ('Análisis de datos', 12), ('Patrones de diseño', 12), ('Arquitectura de soluciones', 12), ('Microsoft Power BI', 12), ('Spring Framework', 11), ('Arquitectura de datos', 11), ('Big data', 11), ('Requisitos técnicos', 11), ('Liderazgo', 11), ('Redacción', 11), ('Ingeniería', 11), ('Aptitudes de organización', 11), ('SAP ERP', 11), ('Salesforce.com', 11), ('React Native', 11), ('Jenkins', 11), ('XML', 11), ('Stack', 11), ('Proceso de ventas', 11), ('Aplicaciones web', 11), ('Contenedorización', 10), ('Integración continua y entrega continua (CI/CD)', 10), ('Representational State Transfer', 10), ('Arquitectura', 10), ('Root Cause', 10), ('Desarrollo de aplicaciones web', 10), ('ABAP', 10), ('MySQL', 10), ('C++', 9), ('Depuración de programas', 9), ('Docker', 9), ('HTML5', 9), ('Control de versiones', 9), ('GitLab', 9), ('Análisis financiero', 9), ('Experiencia de usuario', 9), ('Finanzas', 9), ('Lenguajes de programación', 9), ('Gobierno de datos', 9), ('Arquitectura orientada a servicios (SOA)', 9), ('Visualización de datos', 9), ('Desarrollo de API', 9), ('Diseño para Android', 9), ('Optimización', 9), ('Scripts de pruebas', 9), ('Planificación de pruebas', 9), ('Comunicación oral', 9), ('Revisión de código', 9), ('JSON', 9), ('Gestión de relaciones con clientes (CRM)', 9), ('Buena práctica clínica', 8), ('Administración de sistemas Linux', 8), ('SAP FICO', 8), ('SAP NetWeaver', 8), ('PySpark', 8), ('Ansible', 8), ('Preventas', 8), ('Estrategias de integración', 8), ('Ingeniería de fiabilidad de sitios', 8), ('Herramientas para desarrolladores', 8), ('.NET Core', 8), ('Arquitectura de dispositivos móviles', 8), ('Satisfacción del cliente', 8), ('Minería de datos', 8), ('MongoDB', 8), ('Lado del servidor', 8), ('Snowflake cloud', 8), ('Servicio de atención al cliente', 8), ('Pruebas manuales', 8), ('Automatización robótica de procesos', 8), ('SOAP', 8), ('Ajuste de rendimiento', 7), ('Sistema de gestión de bases de datos (SGBD)', 7), ('Scala', 7), ('Struts', 7), ('Multi-functional', 7), ('Secuencia de comandos', 7), ('Animación tradicional', 7), ('Pensamiento crítico', 7), ('Diseño de experiencia de usuario (UX)', 7), ('Reconocimiento de patrones', 7), ('Telecomunicaciones', 7), ('Consultoría', 7), ('Desarrollo Full Stack', 7), ('Visualización', 7), ('Aseguramiento', 7), ('Microsoft Office', 7), ('Selenium', 7), ('Informática sin servidor', 7), ('PL/SQL', 7), ('Diseño de bases de datos', 7), ('Calidad de datos', 7), ('Procesos de negocio', 7), ('Gestión de cuentas', 7), ('PHP', 7), ('Ejecución de proyectos', 7), ('Appium', 7), ('Investigación de mercado', 7), ('Control de calidad', 7), ('Servicios web', 6), ('Implantación de software', 6), ('B2', 6), ('Azure Data Factory', 6), ('Networking', 6), ('Proyectos de migración', 6), ('Pruebas de software', 6), ('Módulo SAP SD', 6), ('Análisis de problemas', 6), ('Administración de sistemas', 6), ('Infraestructura como código (IaC)', 6), ('Servicio de asistencia técnica', 6), ('Analítica', 6), ('Prestación de servicios', 6), ('Snowflake', 6), ('Gestión de productos', 6), ('Nivel de servicio de contratos', 6), ('Pruebas funcionales', 6), ('Base de datos relacional', 6), ('Gráficos en 2D', 6), ('Data Caching', 6), ('SAP S/4HANA', 6), ('Demostración de productos', 6), ('Planificación de recursos empresariales (ERP)', 6), ('Elaboración de informes', 6), ('Elaboración de informes financieros', 6), ('Framework web', 6), ('Gestión de datos', 6), ('Cuentas a pagar', 6), ('NetSuite', 6), ('Ingenieros civiles', 6), ('Análisis forense', 6), ('Modelo de datos', 6), ('Hablar en público', 6), ('Pruebas', 6), ('Seguro suplementario', 6), ('Windows Server', 5), ('Functionality', 5), ('Atención al cliente', 5), ('System Performance', 5), ('Especificaciones técnicas', 5), ('Datos maestros', 5), ('SAP Controlling (CO)', 5), ('Consultoría tecnológica', 5), ('Escucha activa', 5), ('Veeam', 5), ('Buscar', 5), ('Openshift', 5), ('Wireframing', 5), ('Migración de datos', 5), ('Manipulación de datos', 5), ('Lenguaje unificado de modelado (UML)', 5), ('Comunicación interpersonal', 5), ('Servicios en la nube', 5), ('Procedimientos de almacenado', 5), ('Implementación de soluciones', 5), ('Asesor técnico', 5), ('Ejecución de pruebas', 5), ('Competencias transversales', 5), ('Desarrollo web', 5), ('Procesamiento de lenguaje natural', 5), ('Herramientas de automatización de pruebas', 5), ('Gestión de servicios de TI', 5), ('Tableau', 5), ('Maven', 5), ('Ionic Framework', 5), ('Doctrine', 5), ('Relación con el cliente', 5), ('Automatización de la compilación', 5), ('JUnit', 5), ('Selenium WebDriver', 5), ('NoSQL', 5), ('Desarrollo empresarial', 5), ('Vue.js', 5), ('Ciberseguridad', 5), ('Arquitectura del almacén de datos', 5), ('Sistema de seguimiento de errores', 5), ('Análisis de causa raíz', 5), ('Protocolos de comunicación', 4), ('Vapor', 4), ('Customer Requirements', 4), ('Administración de bases de datos', 4), ('Apache Spark', 4), ('Planificación de negocios', 4), ('Airflow', 4), ('Dirección técnica', 4), ('Diseño de sistemas', 4), ('Handover', 4), ('VxRail', 4), ('Protocolo de transferencia de hipertexto (HTTP)', 4), ('Seguridad de redes', 4), ('Azure Kubernetes Service (AKS)', 4), ('Marketing digital', 4), ('Unix', 4), ('Usabilidad', 4), ('Django', 4), ('IA generativa', 4), ('Modelo-vista-presentador (MVP)', 4), ('Coaching', 4), ('Diseño web adaptable', 4), ('Salesforce Sales Cloud', 4), ('Facilidad de adaptación', 4), ('Documentación de proyectos', 4), ('SOQL', 4), ('Microsoft Power Automate', 4), ('Microsoft PowerApps', 4), ('Sistemas de gestión de contenidos (CMS)', 4), ('Tecnologías de la información y la comunicación', 4), ('Firebase', 4), ('GraphQL', 4), ('Amazon RDS', 4), ('Ingeniería informática', 4), ('Ventas técnicas', 4), ('Microsoft Dynamics', 4), ('OWASP', 4), ('Calidad del servicio', 4), ('Compromiso', 4), ('SAP FI', 4), ('Informes', 4), ('Ingesta de datos', 4), ('Large Language Models (LLM)', 4), ('Client Requirements', 4), ('New Concepts', 4), ('Diseño técnico', 4), ('Implementación de software', 4), ('Multithreading', 4), ('B1', 4), ('Gestión de configuración', 4), ('JIRA', 4), ('Validación de datos', 4), ('Formación', 4), ('Gestión documental', 4), ('Seguimiento', 4), ('Ciclo de vida de desarrollo de software (SDLC)', 4), ('Bloomberg', 4), ('Generación de contactos', 4), ('Llamadas en frío', 4), ('Cucumber', 4), ('Trabajo independiente', 4), ('Software', 4), ('Modelos estadísticos', 4), ('AngularJS', 4), ('Document Object Model', 4), ('New Relic', 4), ('Framework de automatización de pruebas', 4), ('Análisis de negocio', 4), ('Base de datos SQL', 4), ('Diseño de software', 4), ('Conciliación de cuentas', 4), ('Kotlin', 4), ('Privacidad de datos', 4), ('Pruebas de integración', 4), ('Escaneo de vulnerabilidades', 4), ('Evaluación de vulnerabilidad', 4), ('Pruebas de penetración', 4), ('Vulnerability', 4), ('Contabilidad', 4), ('Seguridad de la información', 4), ('Administración de la caja registradora', 4), ('Automation Anywhere', 4), ('Cumplimiento de estándares', 4), ('Seguimiento de defectos', 4), ('Consola', 3), ('Perforce', 3), ('Sockets', 3), ('Windows', 3), ('AJAX', 3), ('Adobe Experience Manager', 3), ('Gestión de configuración de software', 3), ('Project Plus', 3), ('Oracle RAC', 3), ('Portugués', 3), ('Ciclo de vida del software', 3), ('Gestión de lanzamientos', 3), ('Administración de base de datos de Oracle', 3), ('Administración', 3), ('Configuración de sistemas', 3), ('Seguridad', 3), ('Apache Camel', 3), ('Interfaces de programación de aplicaciones empresariales (BA…', 3), ('Google BigQuery', 3), ('Certificación IBM', 3), ('WebSphere Application Server', 3), ('Símbolo del sistema', 3), ('Sistemas operativos', 3), ('AWS Glue', 3), ('Amazon S3', 3), ('Office 365', 3), ('Estrategia', 3), ('Propuestas de valor', 3), ('Búsqueda de candidatos', 3), ('Correo', 3), ('Disponibilidad', 3), ('Presupuestos', 3), ('Proyectos de tecnología de la información', 3), ('Bitbucket', 3), ('Análisis de mercados', 3), ('Pensamiento de diseño', 3), ('Prueba de usabilidad', 3), ('Enrutadores', 3), ('Logics', 3), ('Servicios administrados', 3), ('Figma', 3), ('Alemán', 3), ('Comercial', 3), ('Ingeniería civil', 3), ('Preparación de propuestas', 3), ('Desarrolladores', 3), ('Análisis de requisitos', 3), ('Integración de datos', 3), ('Medios de comunicación social', 3), ('ITIL', 3), ('Oracle Application Express', 3), ('Salesforce Lightning', 3), ('Visual Force', 3), ('Experiencia del cliente', 3), ('Level of Detail (LOD)', 3), ('Aprendizaje automático', 3), ('Desarrollo de aplicaciones', 3), ('Angular Material', 3), ('Gestión de APIs Apigee', 3), ('Microsoft Outlook', 3), ('Lightning Web Components', 3), ('Programación Apex', 3), ('Apache Kafka', 3), ('Pruebas de validación', 3), ('Centro de datos', 3), ('Corrección de textos', 3), ('Edición', 3), ('Azure DevOps', 3), ('Requisitos de software', 3), ('SwiftUI', 3), ('Soluciones móviles', 3), ('Líneas de tiempo', 3), ('Language Modeling', 3), ('Gestión financiera', 3), ('Estrategia de ventas', 3), ('Tendencias tecnológicas', 3), ('Ventas y marketing', 3), ('Requisitos funcionales', 3), ('Azure Databricks', 3), ('Requisitos del usuario', 3), ('Sistemas de pago', 3), ('Azure DevOps Server', 3), ('Amazon EC2', 3), ('Hojas de ruta estratégicas', 3), ('Ventas complejas', 3), ('Administración logística', 3), ('Venta consultiva', 3), ('Soluciones de tecnología', 3), ('Compensation', 3), ('Operaciones de venta', 3), ('Elaboración de modelos financieros', 3), ('Vanilla', 3), ('ASP.NET Web API', 3), ('LINQ', 3), ('Diseño visual', 3), ('Transact-SQL (T-SQL)', 3), ('Clientes internos', 3), ('Visual Basic .NET (NET)', 3), ('Visual Studio', 3), ('Ofimática', 3), ('Elastic Load Balancing', 3), ('Elasticsearch', 3), ('VMware', 3), ('Preparación de datos', 3), ('Flask', 3), ('ESLint', 3), ('Redux.js', 3), ('Equipos multidisciplinarios', 3), ('Software de código abierto', 3), ('Frameworks de PHP', 3), ('Ingeniería de ventas', 3), ('Ingeniería de fiabilidad', 3), ('Ingeniería del caos', 3), ('Opsgenie', 3), ('Access Management', 3), ('OAuth', 3), ('Proyectos de desarrollo', 3), ('Groovy', 3), ('Ingeniería de control de calidad', 3), ('SQL Server Integration Services (SSIS)', 3), ('Hadoop', 3), ('Automatización de procesos', 3), ('Mantenimiento y reparaciones', 3), ('API de Postman', 3), ('Pruebas API', 3), ('Pruebas de regresión', 3), ('Historias de usuarios', 3), ('Mockito', 3), ('Inversiones', 3), ('Desarrollo Salesforce.com', 3), ('Normativas de cumplimiento', 3), ('Seguridad de la aplicación', 3), ('Eclipse', 3), ('Calificación de leads', 3), ('Desarrollo de relaciones', 3), ('Sociología', 3), ('Analista financiero autorizado', 3), ('Banca', 3), ('Oracle Cloud', 3), ('Gestión de vulnerabilidades', 3), ('Sistemas de software', 3), ('Android SDK', 3), ('Aplicaciones nativas en la nube', 3), ('Amazon Simple Queue Service (SQS)', 3), ('JMeter', 3), ('Desarrollo Java', 3), ('Jest', 3), ('Venta directa', 3), ('Estrategia empresarial', 3), ('Activos fijos', 3), ('Estados financieros', 3), ('Atención de clientes en banca', 3), ('Divisa', 3), ('Ingresos', 3), ('Transacciones financieras', 3), ('Venta cruzada', 3), ('Supermercados', 3), ('UiPath', 3), ('Java Database Connectivity (JDBC)', 3), ('Proyectos de software', 3), ('Evaluaciones psicológicas', 3), ('Psicología', 3), ('Psicología clínica', 3), ('Salud mental', 3), ('Terapia para la salud mental', 3), ('Virtualización', 2), ('Apache Sling', 2), ('Diseño de plantillas', 2), ('JCR', 2), ('Plantillas', 2), ('Akamai', 2), ('CI', 2), ('SQL Tuning', 2), ('Language Skills', 2), ('Disparadores de base de datos', 2), ('Industry standards', 2), ('Data Guard', 2), ('RMAN', 2), ('Siebel Systems', 2), ('Planificación de costes', 2), ('Costes', 2), ('DWH', 2), ('Gestión de redes', 2), ('AWS Lambda', 2), ('Optimización para motores de búsqueda (SEO)', 2), ('Transformación digital', 2), ('Visión por computador', 2), ('Artifactory', 2), ('Migración a la nube de AWS', 2), ('Capacidad analítica', 2), ('Suministros', 2), ('Mockups', 2), ('Circuitos', 2), ('Conmutación de paquetes', 2), ('Cortafuegos', 2), ('Grupos de trabajo', 2), ('Análisis de bases de datos', 2), ('Desarrollo de procesos', 2), ('Indicadores clave de desempeño', 2), ('Inteligencia empresarial', 2), ('Ejecutivos de cuentas', 2), ('Percepción de la marca', 2), ('Branding', 2), ('Amazon Advertising', 2), ('SAP Projects', 2), ('Lightning', 2), ('Salesforce DX', 2), ('Diseño de nivel', 2), ('Comercio electrónico', 2), ('Gestión de contenidos', 2), ('Sistemas de gestión', 2), ('Forefront', 2), ('Opiniones sobre productos', 2), ('Requisitos del sistema', 2), ('Resolución de cuestiones', 2), ('Multi-national Teams', 2), ('AWS CloudFormation', 2), ('Bootstrap', 2), ('Shopify', 2), ('Sistemas distribuidos', 2), ('Frameworks de Java', 2), ('SonarQube', 2), ('Administración de oficinas', 2), ('Catalogue Design', 2), ('Nimble', 2), ('Programación de sistemas', 2), ('Fuentes de datos', 2), ('Gestión de incidencias', 2), ('Industria maderera', 2), ('Resolución colaborativa de problemas', 2), ('Bash', 2), ('Container Orchestration', 2), ('Gestión de sistemas', 2), ('Gradle', 2), ('CO-PA', 2), ('CO-PCA', 2), ('Consultoría SAP', 2), ('Patrón', 2), ('UIKit', 2), ('Smartforms', 2), ('ASP.NET', 2), ('Sap Fiori', 2), ('SAP MM', 2), ('Tecnología de Cisco', 2), ('Análisis de crédito', 2), ('Análisis de informes', 2), ('Development Approvals (Land)', 2), ('Seguro de salud', 2), ('CompTIA', 2), ('Reflexión estratégica', 2), ('Seguridad de Cloud', 2), ('Servicio centrado en el cliente', 2), ('Plataformas móviles', 2), ('Sistemas tolerantes a fallos', 2), ('Sqoop', 2), ('Procesos de pruebas', 2), ('Comprensión técnica', 2), ('Rentabilidad de la inversión', 2), ('Creación de relaciones', 2), ('Electron.js', 2), ('Resiliencia', 2), ('Usage Analysis', 2), ('Estándares de diseño', 2), ('Cloudera', 2), ('Políticas y procedimientos', 2), ('Autodesk 3ds Max', 2), ('Diseño arquitectónico', 2), ('Indización', 2), ('Motores de búsqueda', 2), ('Administración de sistemas operativos', 2), ('Microsoft Dynamics CRM', 2), ('Diseño de soluciones técnicas', 2), ('Ejecución de pozos', 2), ('SQL Server Analysis Services (SSAS)', 2), ('Protocolo de Internet (IP)', 2), ('Sistema de gestión de bases de datos relacionales', 2), ('Sistemas de control distribuido', 2), ('Aseguramiento de la calidad de los datos', 2), ('Lenguaje de consulta (query)', 2), ('Optimización de consultas', 2), ('Comercio', 2), ('Desarrollo de oportunidades de negocio', 2), ('Gestión de crisis', 2), ('Gestión de programas', 2), ('Fleet Management Software', 2), ('Cuentas a cobrar', 2), ('Análisis competitivo', 2), ('Crecimiento acelerado', 2), ('Experiencia en el sector', 2), ('Gestión administrativa', 2), ('Venta de servicios', 2), ('Aptitudes para la coordinación', 2), ('Evaluaciones de rendimiento', 2), ('Investigación primaria', 2), ('Investigación secundaria', 2), ('Coordinación de reuniones', 2), ('Para empresas (B2B)', 2), ('Sistema de planificación de recursos empresariales', 2), ('Banca de inversión', 2), ('Cartera de clientes', 2), ('Opportunity Tracking', 2), ('Apache', 2), ('Apache Airflow', 2), ('jQuery', 2), ('Creación de informes', 2), ('Pruebas del sistema', 2), ('Alta disponibilidad', 2), ('Entity Framework', 2), ('Plataforma como servicio (PaaS)', 2), ('Visual Basic for Applications (VBA)', 2), ('Desarrollo de proyectos', 2), ('Diseño gráfico', 2), ('Platform Management', 2), ('Ingeniería de sistemas', 2), ('Despliegue de sistemas', 2), ('JBoss Application Server', 2), ('Genexus', 2), ('Edición de textos', 2), ('Principios SOLID', 2), ('Máquinas virtuales', 2), ('Protocolo de configuración de anfitrión dinámicos (DHCP)', 2), ('Splunk', 2), ('Desarrollo de módulos', 2), ('Drupal', 2), ('Technical English', 2), ('TIBCO', 2), ('Occupational Risk Prevention', 2), ('Cumplimiento de la normativa', 2), ('Distribución de energía eléctrica', 2), ('Ejecución de obras', 2), ('Empresas de diseño', 2), ('Informes técnicos', 2), ('Public Communications', 2), ('Solution-oriented', 2), ('Laravel', 2), ('Informes de gastos', 2), ('Profesionalidad', 2), ('Autenticación', 2), ('Keycloak', 2), ('OpenID', 2), ('Unreal Engine', 2), ('Planificación de capacidad', 2), ('Estrategia de datos', 2), ('Análisis de datos estadísticos', 2), ('Procedimientos almacenados T-SQL', 2), ('Estructuras de datos', 2), ('Trabajo virtual', 2), ('Entorno Agile', 2), ('Pruebas de móvil', 2), ('SQL de Azure', 2), ('Matplotlib', 2), ('NumPy', 2), ('Pandas (Software)', 2), ('Mantenimiento', 2), ('Análisis estadístico', 2), ('Análisis predictivo', 2), ('Prediction', 2), ('Gestión de la ingeniería', 2), ('R (Lenguaje de programación)', 2), ('BMC Control-M', 2), ('SAPUI5', 2), ('Hive', 2), ('Desarrollo de innovación', 2), ('Indemnización', 2), ('Marketing de correo electrónico', 2), ('GitHub', 2), ('ServiceNow', 2), ('Economía', 2), ('Análisis de marketing', 2), ('Campañas de marketing', 2), ('Diseño', 2), ('Flujos de usuario', 2), ('Specifications', 2), ('Gestión de cambio estructural', 2), ('ISO 9001', 2), ('Servicio de campo', 2), ('Soporte para impresoras', 2), ('Asesoramiento y orientación', 2), ('Operaciones de seguridad', 2), ('Dispositivos móviles', 2), ('Certificación ITIL', 2), ('Citrix', 2), ('Protocolos de seguridad', 2), ('Respuesta ante incidentes', 2), ('Procesamiento de transacciones online', 2), ('Prueba de productos', 2), ('Electricidad', 2), ('Diseño de servicios', 2), ('Admi

In [23]:
for sublist in filtered_df['Apts']:
    print(sublist)

['Buena práctica clínica', 'Comunicación', 'Contenedorización', 'Dirección de equipos', 'Go', 'Google Cloud', 'Inglés', 'Microservicios', 'Programación de aplicaciones', 'Servicios web', 'Todos los filtros']
['C++', 'Consola', 'Depuración de programas', 'Fiabilidad', 'Git', 'Perforce', 'Programación', 'Protocolos de comunicación', 'Sockets', 'Vapor', 'Todos los filtros']
['Comunicación', 'Resolución de problemas']
['DevOps', 'Docker', 'Gestión de parches', 'GlassFish', 'Linux', 'Virtualización', 'Windows', 'Windows Server', 'Todos los filtros']
['AJAX', 'Adobe Experience Manager', 'Apache Sling', 'Comunicación', 'Diseño de plantillas', 'Functionality', 'HTML', 'Hojas de estilos en cascada (CSS)', 'JCR', 'Plantillas']
['Amazon Web Services (AWS)', 'Bases de datos', 'Comunicación', 'Implantación de software', 'Integración continua y entrega continua (CI/CD)', 'Java', 'Kubernetes', 'Microservicios', 'Spinnaker', 'TypeScript']
['Amazon Web Services (AWS)', 'HTML', 'HTML5', 'Hojas de estilos en cascada (CSS)', 'Java', 'JavaScript', 'Node.js', 'Oracle Database', 'Spring Boot', 'Todos los filtros']
['Administración de sistemas Linux', 'Akamai', 'CAPAs', 'CI', 'Desarrollo de software', 'DevOps', 'Gestión de configuración de software', 'Infraestructura en la nube', 'Inglés', 'Terraform', 'Todos los filtros']
['Gestión de proyectos', 'Oficina de gestión de proyectos (PMO)', 'Project Plus', 'Scrum', 'Todos los filtros']
['Atención al cliente', 'Comunicación', 'Habilidades sociales', 'Inglés', 'Oracle RAC', 'Portugués', 'Presentaciones', 'Resolución de problemas', 'SQL Tuning', 'System Performance']
['Atención al detalle', 'Automatización de pruebas', 'B2', 'Ciclo de vida del software', 'Control de versiones', 'Desarrollo de software', 'DevOps', 'Gestión de lanzamientos', 'Inglés', 'Language Skills', 'Todos los filtros']
['Azure Data Factory', 'Extraer, transformar y cargar (ETL)', 'Microsoft Azure', 'Representational State Transfer', 'SoapUI', 'Todos los filtros']
['Implementaciones Oracle ERP', 'Software B2B', 'Todos los filtros']
['Customer Requirements', 'Disparadores de base de datos', 'Especificaciones técnicas', 'Gobernanza, riesgo y cumplimiento (GRC)', 'Gobierno de TI', 'Grabación de vídeo', 'Industry standards', 'Liderazgo funcional', 'Necesidades empresariales', 'Open Pages']
['Administración de base de datos de Oracle', 'Administración de bases de datos', 'Ajuste de rendimiento', 'Data Guard', 'GoldenGate', 'HP-UX', 'RMAN', 'Resolución de incidencias', 'SQL*Plus', 'Sistema de gestión de bases de datos (SGBD)']
['Todos los filtros']
['Administración', 'Amazon Virtual Private Cloud (VPC)', 'Cola de mensajes', 'Configuración de sistemas', 'Consultas', 'Networking', 'Seguridad', 'Todos los filtros']
['Todos los filtros']
['Siebel Systems']
['Apache Spark', 'Buena práctica clínica', 'Ciencia de datos', 'Extraer, transformar y cargar (ETL)', 'Google Cloud', 'Ingeniería de datos', 'Inglés', 'Proyectos de migración', 'Python', 'Scala']
['Dirección de equipos', 'Planificación de negocios', 'Trabajo en equipo']
['Angular', 'Apache Camel', 'Desarrollo front end', 'Enrutamiento dinámico', 'Java', 'PostgreSQL', 'Pruebas de software', 'Spring Boot', 'Spring Framework', 'Struts']
['Capacidad de análisis']
['Contabilidad exigida por ley', 'Datos maestros', 'Estándares de contabilidad', 'Inglés', 'Ledger', 'Liderazgo de equipos', 'Negociación', 'Planificación de costes', 'Productos SAP', 'SAP Controlling (CO)']
['Colaboración con clientes', 'Costes', 'Datos maestros', 'Interfaces de programación de aplicaciones empresariales (BA…', 'Multi-functional', 'Módulo SAP SD', 'Nube híbrida', 'Planificación de costes', 'Resolución creativa de problemas', 'SAP FICO']
['Airflow', 'Canalizaciones de datos', 'Desarrollo de software', 'Desarrollo web back end', 'Gestión de flujos de trabajo', 'Google BigQuery', 'Google Cloud Dataflow', 'Ingeniería de datos', 'Kubeflow', 'Modelado de datos']
['Automatización', 'Bases de datos', 'GNU/Linux', 'Inglés', 'Kubernetes', 'Linux', 'Python', 'Secuencia de comandos', 'Terraform', 'Windows Server', 'Todos los filtros']
['Análisis de problemas', 'Arquitectura', 'Arquitectura de datos', 'Comunicación', 'DWH', 'Dirección técnica', 'Diseño de sistemas', 'Documentación técnica', 'Extraer, transformar y cargar (ETL)', 'Scala']
['Certificación IBM', 'Consultoría tecnológica', 'Escucha activa', 'Handover', 'Root Cause', 'SAP HANA', 'SAP NetWeaver', 'Veeam', 'VxRail', 'WebSphere Application Server']
['Animación tradicional', 'C#', 'C++', 'Curl', 'Depuración de programas', 'Gráficos', 'Programación en C', 'Protocolo de transferencia de hipertexto (HTTP)', 'Root Cause', 'Símbolo del sistema', 'Todos los filtros']
['Administración de sistemas', 'Ciencias de la computación', 'Gestión de redes', 'Oracle Data Integrator', 'Resolución de incidencias', 'Seguridad de redes', 'Sistemas operativos', 'Soporte técnico', 'System Performance', 'Tecnología de la información']
['AWS Glue', 'AWS Lambda', 'Amazon Redshift', 'Amazon S3', 'Amazon Web Services (AWS)', 'Análisis de clústers', 'Git', 'GitLab', 'Guiones shell', 'PySpark', 'Sistema de gestión de bases de datos (SGBD)', 'Todos los filtros']
['Administración de sistemas Linux', 'Office 365', 'Python', 'Todos los filtros']
['Azure Kubernetes Service (AKS)', 'C#', 'Gestión de configuración de software', 'Hojas de estilos en cascada (CSS)', 'Microservicios', 'Microsoft Azure', 'Microsoft SQL Server', 'Suscripciones', 'Terraform', 'Trabajo en equipo', 'Todos los filtros']
['Amazon Web Services (AWS)', 'Big data', 'Extraer, transformar y cargar (ETL)', 'Infraestructura como código (IaC)', 'Metodologías ágiles', 'PySpark', 'Python', 'Requisitos técnicos', 'Todos los filtros']
['Angular']
['Amazon Web Services (AWS)', 'Ansible', 'Git', 'Implantación de software', 'Java', 'JavaScript', 'Microsoft Azure', 'Python', 'Terraform', 'Todos los filtros']
['AWS Glue', 'Almacenamiento de datos', 'Amazon Web Services (AWS)', 'Bases de datos', 'Big data', 'Ciencia de datos', 'Extraer, transformar y cargar (ETL)', 'Hojas de estilos en cascada (CSS)', 'Infraestructura en la nube', 'Ingeniería de datos', 'Todos los filtros']
['Servicio de asistencia técnica', 'Todos los filtros']
['Estrategia', 'Estrategia digital', 'Google Analytics', 'Marketing de redes sociales', 'Marketing digital', 'Medios digitales', 'Optimización para motores de búsqueda (SEO)', 'SMB', 'Trabajo en equipo', 'Transformación digital', 'Todos los filtros']
['Evaluación', 'Inglés', 'Inteligencia artificial', 'Liderazgo', 'Metodologías ágiles', 'Posicionamiento', 'Propuestas de valor', 'Python', 'Visión por computador']
['Buscar', 'Búsqueda de candidatos', 'Correo', 'Disponibilidad', 'Plataforma', 'Presupuestos', 'Proyectos de tecnología de la información', 'Salario', 'Tecnología de la información', 'Weather']
['Amazon Web Services (AWS)', 'Ansible', 'Artifactory', 'Bitbucket', 'Docker', 'Linux', 'Migración a la nube de AWS', 'Openshift', 'Python', 'Terraform', 'Unix', 'Todos los filtros']
['Analítica de datos', 'Aplicaciones de los Sistemas de Información Geográfica (SIG)', 'ArcGIS Desktop', 'ArcGIS Pro', 'ArcMap', 'Bases de datos espaciales', 'Comunicación', 'GIS Software', 'Sistemas de Información Geográfica', 'Teledetección']
['Azure Data Factory', 'Extraer, transformar y cargar (ETL)', 'Microsoft Azure', 'Todos los filtros']
['Abastecimiento estratégico', 'Análisis de mercados', 'Análisis financiero', 'Capacidad analítica', 'Capacidad técnica', 'Capital Expenditures', 'Desarrollo de proveedores', 'Pensamiento crítico', 'Strategic Supplier Development', 'Suministros']
['Diseño de experiencia de usuario (UX)', 'Diseño de la interfaz de usuario', 'Experiencia de usuario', 'Lean UX', 'Mockups', 'Pensamiento de diseño', 'Prueba de usabilidad', 'Redacción', 'Usabilidad', 'Wireframing']
['Amazon Web Services (AWS)', 'Django', 'Inglés', 'Python', 'React.js', 'Todos los filtros']
['Angular', 'Circuitos', 'Conmutación de paquetes', 'Cortafuegos', 'Enrutadores', 'Fiabilidad', 'Grupos de trabajo', 'Inglés', 'Java', 'Soporte técnico', 'Todos los filtros']
['AWR', 'Atención al cliente', 'Comunicación', 'Migración de datos', 'Oracle RAC', 'Portugués', 'Presentaciones', 'Resolución de problemas', 'SQL', 'SQL Tuning', 'Todos los filtros']
['Capacidad de análisis', 'Comunicación', 'Comunicación técnica', 'Gestión de proyectos', 'IA generativa', 'Inglés', 'Inteligencia artificial', 'Logics', 'Manipulación de datos', 'Resolución de problemas']
['Bienes de consumo', 'Clear Vision', 'Comunicación', 'Desarrollo de casos empresariales', 'Finanzas', 'Investigación', 'Liderazgo de equipos', 'Modelo-vista-presentador (MVP)', 'Preparación de casos empresariales', 'Projecting']
['Ciencia de datos', 'Ciencias de la computación', 'Difusión', 'Eventos internacionales', 'Inteligencia artificial', 'Logics', 'Modelado y simulación', 'Necesidades empresariales', 'Reconocimiento de patrones', 'Stable Diffusion']
['Arquitectura', 'Customer Requirements', 'Diagram Design', 'Gestión de configuración de software', 'Java', 'JavaScript', 'Lenguaje unificado de modelado (UML)', 'Lenguajes de programación', 'Programación', 'TypeScript', 'Todos los filtros']
['Ingeniería', 'Servicios administrados', 'Telecomunicaciones', 'Todos los filtros']
['Análisis de bases de datos', 'Aptitudes de organización', 'Bases de datos', 'Comunicación', 'Comunicación interpersonal', 'Desarrollo de procesos', 'Desarrollo del personal', 'Desarrollo organizacional', 'Habilidades sociales', 'Redacción', 'Todos los filtros']
['Analítica', 'Capital intelectual', 'Coaching', 'Comunicación', 'Estrategia corporativa', 'Gestión de líneas', 'Indicadores clave de desempeño', 'Resolución de problemas', 'Servicios al cliente', 'Structured Thinking']
['After Effects', 'Diseño de experiencia de usuario (UX)', 'Diseño de la interfaz de usuario', 'Diseño web adaptable', 'Experiencia de usuario', 'Figma', 'Pensamiento de diseño', 'Prueba de usabilidad', 'Usabilidad', 'Wireframing']
['Ingeniería', 'Servicios administrados', 'Telecomunicaciones', 'Todos los filtros']
['Alemán', 'Análisis de procesos', 'Aptitudes de organización', 'Comunicación', 'Comunicación interpersonal', 'Habilidades sociales', 'Investigación', 'Negociación', 'Trabajo en equipo']
['Comercial', 'Consultoría', 'Ingeniería', 'Ingeniería civil', 'Inteligencia empresarial', 'Liderazgo', 'Liderazgo de proyectos', 'Microsoft Excel', 'Project Plus', 'Ventas']
['Productos SAP', 'SAP ERP', 'Todos los filtros']
['Computación en la nube', 'Comunicación', 'Ejecutivos de cuentas', 'Percepción de la marca', 'Preparación de propuestas', 'Prestación de servicios', 'Preventas', 'Proyectos de migración', 'Servicios en la nube', 'Tecnología de la información', 'Todos los filtros']
['Desarrolladores', 'Gestión sénior de las partes interesadas', 'Ruby on Rails', 'Spring Framework', 'Todos los filtros']
['Análisis de impacto del cambio', 'Asignación de datos', 'Banca, finanzas y seguros', 'Change Requests', 'Computación en la nube', 'Necesidades empresariales', 'Obtención de requisitos', 'Salesforce Sales Cloud', 'Salesforce Service Cloud', 'Salesforce.com']
['Analítica de datos', 'Análisis de requisitos', 'Dirección técnica', 'Extraer, transformar y cargar (ETL)', 'Gobierno de datos', 'Integración de datos', 'Microsoft Azure', 'Orientación de equipos', 'Proyectos de migración', 'Servicios de datos', 'Todos los filtros']
['Branding', 'Comunicación', 'Comunicación escrita', 'Contenido atractivo', 'Facilidad de adaptación', 'Gestión de medios', 'Gestión de redes sociales', 'Medios de comunicación social', 'Optimización de las redes sociales (SMO)', 'Trabajo en equipo']
['Capacidad de análisis', 'Documentación de proyectos', 'Extraer, transformar y cargar (ETL)', 'Google Cloud', 'Ingeniería de datos', 'Procedimientos de almacenado', 'PySpark', 'Python', 'Scala', 'Snowflake']
['Amazon Advertising', 'ITIL', 'SAP FICO', 'SAP Projects', 'Todos los filtros']
['Airflow', 'Atención al detalle', 'Bases de datos', 'Extraer, transformar y cargar (ETL)', 'Google BigQuery', 'Google Cloud', 'Ingeniería de datos', 'Inglés', 'Python', 'SQL']
['Estrategias de integración', 'Formación de usuarios', 'Lightning', 'Oracle Application Express', 'Resolución de problemas', 'SOQL', 'Salesforce CPQ', 'Salesforce DX', 'Salesforce Lightning', 'Visual Force']
['Ajuste', 'Desarrollo de videojuegos', 'Diseño de juegos', 'Diseño de nivel', 'Inteligencia artificial', 'Juegos para móviles', 'Jugabilidad', 'Maya', 'Mecánicas de juego', 'Unreal Engine 4']
['Automatización', 'Ciencias de la computación', 'Comunicación', 'Diseño de la interfaz de usuario', 'Hojas de estilos en cascada (CSS)', 'Microsoft Power Automate', 'Microsoft PowerApps', 'Microsoft SQL Server', 'Necesidades empresariales', 'Resolución de problemas']
['Expertos en la materia', 'Fiabilidad', 'GitLab', 'Go', 'Infraestructura como código (IaC)', 'Ingeniería de fiabilidad de sitios', 'Ingeniería de sonido', 'Modos de falla', 'Programa federal de gestión de riesgos y autorizaciones (Fed…', 'Sistemas de producción']
['Administración de recursos digitales', 'Aplicaciones móviles', 'Comercio electrónico', 'Content Modeling', 'Gestión de contenidos', 'Gestión de productos', 'Gestión de productos técnicos', 'Inglés', 'Sistemas de gestión', 'Sistemas de gestión de contenidos (CMS)']
['Comunicación', 'Escucha activa', 'Experiencia del cliente', 'Forefront', 'Level of Detail (LOD)', 'Nivel de servicio de contratos', 'Opiniones sobre productos', 'Root Cause', 'Tecnología de la información', 'Tecnologías de la información y la comunicación']
['Comunicación', 'Desarrollo de iOS', 'Documentación técnica', 'Especificaciones técnicas', 'Swift (lenguaje de programación)', 'iOS', 'Todos los filtros']
['Arquitectura', 'Arquitectura de software', 'Arquitectura orientada a servicios (SOA)', 'Desarrollo de sistemas', 'Especificaciones técnicas', 'Microservicios', 'Preparación de propuestas', 'Presentaciones', 'Preventas', 'Requisitos del sistema']
['Desarrollo de aplicaciones móviles', 'Diseño web adaptable', 'Hojas de estilos en cascada (CSS)', 'Metodologías ágiles', 'Prueba unitaria', 'Pruebas funcionales', 'React Native', 'React.js', 'Scrum', 'TypeScript']
['Aprendizaje automático', 'Ciencia de datos', 'Diapositivas', 'IA generativa', 'Inglés hablado', 'Inteligencia artificial', 'Lado del cliente', 'Reconocimiento de patrones', 'Retoques fotográficos', 'Visión por computador', 'Todos los filtros']
['Atención al detalle', 'Capacidad de análisis', 'Comunicación', 'Desarrollo de aplicaciones', 'Desarrollo de software', 'Establecer prioridades del trabajo', 'Necesidades empresariales', 'Procedimientos de almacenado', 'Programación', 'Resolución de cuestiones']
['Aseguramiento de la calidad', 'B2', 'Comunicación', 'Comunicación escrita', 'Estrategias de integración', 'Inglés', 'Marketing', 'Multi-national Teams', 'Negociación', 'Proyectos de integración']
['Angular', 'Angular Material', 'Bases de datos', 'Desarrollo Full Stack', 'Desarrollo front end', 'Hojas de estilos en cascada (CSS)', 'Java', 'JavaScript', 'Transferencia de Estado Representacional (REST)', 'TypeScript']
['Apache Camel', 'Buscar', 'Gestión de APIs Apigee', 'Spring Boot', 'Todos los filtros']
['AWS CloudFormation', 'Administración de sistemas Linux', 'Amazon Web Services (AWS)', 'Capacidad de análisis', 'Comunicación', 'Contenedorización', 'Inglés', 'Kubernetes', 'Networking', 'Resolución de problemas']
['Almacenamiento de datos', 'Analítica de datos', 'Análisis de datos', 'Capacidad de análisis', 'Ciencia de datos', 'Extraer, transformar y cargar (ETL)', 'Ingeniería de datos', 'Inglés', 'Visualización', 'Visualización de datos']
['Bootstrap', 'Diseño web adaptable', 'Firebase', 'Hojas de estilos en cascada (CSS)', 'Inglés', 'Metodologías Agile y Waterfall', 'Node.js', 'React.js', 'Shopify', 'TypeScript']
['Ciencias de la computación', 'Comunicación', 'Desarrollo de iOS', 'Documentación técnica', 'Especificaciones técnicas', 'RxSwift', 'Swift (lenguaje de programación)', 'iOS']
['Desarrollo de aplicaciones web', 'Desarrollo de software', 'Inglés', 'Metodologías Agile y Waterfall', 'Metodologías ágiles', 'Modelo-Vista-Controlador (MVC)', 'Programación', 'Programación orientada a objetos (POO)', 'Ruby', 'Ruby on Rails']
['Desarrollo de aplicaciones web', 'Desarrollo de software', 'Inglés', 'Modelo-Vista-Controlador (MVC)', 'PostgreSQL', 'Programación', 'Programación orientada a objetos (POO)', 'Ruby', 'Ruby on Rails', 'SQL']
['Base de datos relacional', 'Bases de datos', 'Desarrollo web back end', 'Go', 'GraphQL', 'Inglés', 'JavaScript', 'Node.js', 'Sistemas distribuidos', 'TypeScript']
['Amazon RDS', 'Amazon Web Services (AWS)', 'Frameworks de Java', 'Java', 'Spring Boot']
['Amazon Web Services (AWS)', 'Angular', 'Arquitectura orientada a servicios (SOA)', 'Git', 'Integración continua', 'Java', 'Jenkins', 'Microservicios', 'Prueba unitaria', 'SonarQube', 'Spring Boot', 'Transferencia de Estado Representacional (REST)']
['Cargas', 'Productos SAP', 'SAP Basis', 'SAP ERP', 'SAP FICO']
['Administración de oficinas', 'Catalogue Design', 'Ingeniería informática', 'Inglés', 'Microsoft Outlook', 'Nimble', 'Planificación de eventos', 'Servicios de consultoría', 'Siebel Systems', 'Visualización']
['Comunicación', 'Inglés', 'Resolución de incidencias', 'Software como servicio (SaaS)', 'Soporte técnico', 'Trabajo en equipo', 'Ventas técnicas']
['Animación tradicional', 'C#', 'C++', 'Ciencias de la computación', 'Desarrollo de software', 'Gráficos en 2D', 'Programación en C', 'Protocolo de transferencia de hipertexto (HTTP)', 'Símbolo del sistema', 'XML']
['Desarrollo de API', 'Java', 'Lightning Web Components', 'Programación Apex', 'Salesforce.com']
['Aseguramiento de la calidad']
['Android', 'Aplicaciones móviles', 'Data Caching', 'Desarrollo de aplicaciones móviles', 'Desarrollo de software', 'Diseño para Android', 'HTML', 'Herramientas para desarrolladores', 'Hojas de estilos en cascada (CSS)', 'JavaScript']
['Aptitudes de organización', 'Bases de datos', 'Comunicación', 'Comunicación escrita', 'Desarrollo web back end', 'Documentación', 'GitLab', 'Optimización', 'Programación de sistemas', 'Ruby']
['.NET Core', 'SQL']
['.NET Framework', 'App-V', 'Desarrollo de software', 'Metodologías ágiles', 'Microsoft Dynamics', 'Microsoft Power Pages', 'Microsoft PowerApps']
['Aplicaciones móviles', 'Automatización de pruebas', 'Desarrollo de iOS', 'Fuentes de datos', 'Objective-C', 'Programación en C', 'Programación orientada a objetos (POO)', 'Prueba unitaria', 'Swift (lenguaje de programación)', 'iOS']
['Administración de base de datos de Oracle', 'Administración de bases de datos', 'Ajuste de rendimiento', 'Bases de datos', 'Data Guard', 'Extraer, transformar y cargar (ETL)', 'Oracle Database', 'Oracle E-Business Suite', 'RMAN', 'Resolución de incidencias']
['Angular', 'Angular Material', 'Bases de datos', 'Desarrollo Full Stack', 'Desarrollo front end', 'Hojas de estilos en cascada (CSS)', 'Java', 'JavaScript', 'Transferencia de Estado Representacional (REST)', 'TypeScript']
['Aplicaciones móviles', 'Automatización de pruebas', 'Desarrollo de iOS', 'Desarrollo de software', 'Mobile Software Development', 'Objective-C', 'Programación en C', 'Prueba unitaria', 'Swift (lenguaje de programación)', 'iOS']
['Amazon Web Services (AWS)', 'Ansible', 'Artifactory', 'Bitbucket', 'Docker', 'Linux', 'Migración a la nube de AWS', 'Openshift', 'Python', 'Terraform', 'Unix']
['.NET Core', 'Docker']
['Almacenamiento de datos', 'Apache Kafka', 'Bases de datos', 'Ciencia de datos', 'Extraer, transformar y cargar (ETL)', 'Hojas de estilos en cascada (CSS)', 'Ingeniería de datos', 'Optimización', 'Python', 'SQL']
['Capacidad de análisis', 'Ciencias de la computación', 'Comunicación', 'Experiencia de usuario', 'Gestión de asuntos', 'Negociación', 'Oracle Financial Services Analytical Applications (OFSAA)', 'Pruebas de aceptación del usuario', 'Pruebas de validación', 'Requisitos técnicos']

In [24]:
result = pd.DataFrame(top_apts, columns=['Aptitud', 'Frecuencia'])

# Mostrar el DataFrame
result.head(40)

                                            Aptitud  Frecuencia
0                                 Todos los filtros         211
1                                            Inglés         173
2                                      Comunicación         157
3                                              Java          93
4                            Desarrollo de software          86
5                                               SQL          80
6                           Resolución de problemas          78
7                 Hojas de estilos en cascada (CSS)          78
8                                    Bases de datos          75
9                                            Python          75
10                                       JavaScript          67
11                       Ciencias de la computación          62
12                          Desarrollo web back end          51
13                            Capacidad de análisis          46
14                        Amazon Web Services (AWS)          43
15                                  Microsoft Azure          43
16                                          Angular          43
17                                   Microservicios          40
18                                               C#          36
19              Extraer, transformar y cargar (ETL)          35
20                                     Google Cloud          34
21                             Liderazgo de equipos          32
22                                Programación en C          30
23                                      Negociación          29
24                                             HTML          28
25                                      Spring Boot          28
26                        Automatización de pruebas          28
27                                              iOS          28
28  Transferencia de Estado Representacional (REST)          28
29                                           DevOps          27
30                              Atención al detalle          27
31                                 Ciencia de datos          27
32                             Desarrollo front end          27
33                                     Programación          26
34                   Modelo-Vista-Controlador (MVC)          26
35                                Trabajo en equipo          25
36                           Computación en la nube          25
37                                          Android          25
38                             Microsoft SQL Server          24
39               Desarrollo de aplicaciones móviles          24